name: github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
    check-bats-version:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '14'
            - name: Install Truffle
              run: npm install truffle -g
            - name: Install Truffle Dependencies
              run: npm install
            - name: Run Truffle Test with CI=true for Codechecks
              run: CI=true truffle test
